" ################################################################################ 
" ########## The following is for Vundle ##########
" ########## See https://github.com/VundleVim/Vundle.vim ########## 
set nocompatible              " be iMproved, required
filetype off                  " required
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle
Plugin 'VundleVim/Vundle.vim'
" Plugins
Plugin 'tpope/vim-surround'
Plugin 'vim-scripts/LanguageTool'				" spell/syntax checking
Plugin 'vim-scripts/bash-support.vim'
Plugin 'wincent/command-t'
Plugin 'easymotion/vim-easymotion'
Plugin 'Valloric/YouCompleteMe'  				" auto-completion
Plugin 'tpope/vim-fugitive' 					" a git wrapper
Plugin 'altercation/vim-colors-solarized'  		" color theme
Plugin 'vim-airline/vim-airline'				" vim status line
Plugin 'vim-airline/vim-airline-themes'			" color theme for vim status line
" Plugin 'Townk/vim-autoclose'
Plugin 'xolox/vim-misc'							" auto-load vim script (required by xolox/vim-session)
Plugin 'xolox/vim-session'

call vundle#end()            " required
filetype plugin indent on    " required

" ################################################################################ 
" ########## The following is configured for Latex-Suite ##########
" ########## See http://vim-latex.sourceforge.net/documentation/latex-suite/recommended-settings.html ##########
" REQUIRED. This makes vim invoke Latex-Suite when you open a tex file.
filetype plugin on

" IMPORTANT: win32 users will need to have 'shellslash' set so that latex
" can be called correctly.
set shellslash

" IMPORTANT: grep will sometimes skip displaying the file name if you
" search in a singe file. This will confuse Latex-Suite. Set your grep
" program to always generate a file-name.
set grepprg=grep\ -nH\ $*

" OPTIONAL: This enables automatic indentation as you type.
filetype indent on

" OPTIONAL: Starting with Vim 7, the filetype of empty .tex files defaults to
" 'plaintex' instead of 'tex', which results in vim-latex not being loaded.
" The following changes the default filetype back to 'tex':
" let g:tex_flavor='latex' (I (hengxin) changed it to 'xelatex')
let g:Tex_BibtexFlavor = 'bibtex'
let g:tex_flavor='xelatex'
let g:Tex_CompileRule_pdf = 'xelatex --synctex=-1 -src-specials -interaction=nonstopmode -file-line-error-style $*'
let g:Tex_DefaultTargetFormat='pdf'
let g:Tex_FormatDependency_pdf = 'pdf'
" The following is relevant to make LaTeX rerun after biber if necessary: 
" (include all formats for which re-running is to be enabled)
let g:Tex_MultipleCompileFormats='pdf,dvi'
" let g:Tex_ViewRule_pdf =  'SumatraPDF -reuse-instance '

" F2: autosave before compiling
map <f2> :w<cr><leader>ll
" ########## End of configuration for Latex-Suite ##########

syntax on
set number
set relativenumber

" Use the OS clipboard by default
set clipboard=unnamed

set textwidth=100

" [indent](http://stackoverflow.com/a/234578/1833118)
" when indenting with '>', use 4 spaces width
set shiftwidth=4
" show existing tab with 4 spaces width
set tabstop=4
" On pressing tab, insert 4 spaces
" set expandtab

" spell checking
"ignore East Asian characters including Chinese; see http://unix.stackexchange.com/a/192835
set spelllang+=cjk  
setlocal spell

" hide UI elements from GVIM
set guioptions-=m  "menu bar
set guioptions-=T  "toolbar
set guioptions-=r  "scrollbar
" set background=dark

set guifont=Ubuntu\ Mono\ 15

" incremental and highlight search
set incsearch
set hlsearch
set iskeyword+=-
set iskeyword+=@
set iskeyword+=:
set ignorecase
set smartcase

" statusline
set showmode
set title
set showcmd

" Don’t add empty newlines at the end of files
set binary
set noeol

" #################### for netrw: the explorer mode ####################
let mapleader=" "
" enter the explorer mode
nnoremap <leader>e :Explore<cr> 
" enter the explorer mode in a new tab
nnoremap <leader>t :Texplore<cr>
" enter the explorer mode in a vertical split
nnoremap <leader>v :Vexplore<cr>
" enter the explorer mode in a horizontal split
nnoremap <leader>h :Hexplore<cr>
" return to explorer mode
nnoremap <leader>r :Rexplore<cr>
let g:netrw_liststyle=3
" #################### for netrw: the explorer mode ####################


" ########## placeholders ########## 
" ##### See http://vim.wikia.com/wiki/Simple_placeholders #####
" A syntax for placeholders
" Pressing Control-j jumps to the next match.
" inoremap <c-j> <Esc>/<++><CR><Esc>cf>

" Completions using placeholders
" inoremap ) ()<++><Esc>F)i
" inoremap ] []<++><Esc>F]i
" inoremap } {}<++><Esc>F}i
" inoremap > <><++><Esc>F>i
" inoremap ' ''<++><Esc>F'i
" ########## placeholders ########## 

" #################### Plugin Configurations #################### 
" for matchit Plugin
runtime macros/matchit.vim

" for LanguageTool Plugin
let g:languagetool_jar="~/SoftwareService/LanguageTool-3.3/languagetool-commandline.jar"

" ########## for bash-support Plugin ##########
let g:BASH_AuthorName   = 'hengxin'
let g:BASH_Email        = 'hengxin0912@gmail.com'
let g:BASH_Company      = 'ICS@NJU'
" ########## for bash-support Plugin ##########

" ########## for easymotion Plugin ########## 
let g:EasyMotion_do_mapping = 0 " Disable default mappings
let g:EasyMotion_smartcase = 1 " Turn on case insensitive feature

" `<Leader>f{char}` move to {char}
map  <Leader>f <Plug>(easymotion-bd-f)
nmap <Leader>f <Plug>(easymotion-overwin-f)

" `<Leader>w{char}`: move to word
map <Leader>w <Plug>(easymotion-bd-w)
nmap <Leader>w <Plug>(easymotion-overwin-w)

" `s{char}{char}{label}`: move to {char}{char}
map <Leader>s <Plug>(easymotion-overwin-f2)

" JK motions: Line motions
map <Leader>j <Plug>(easymotion-j)
map <Leader>k <Plug>(easymotion-k)

map <Leader>l <Plug>(easymotion-bd-jk)
nmap <Leader>l <Plug>(easymotion-overwin-line)

" Gif config
map <Leader>/ <Plug>(easymotion-sn)
omap <Leader>/ <Plug>(easymotion-tn)

" These `n` & `N` mappings are options. You do not have to map `n` & `N` to EasyMotion.
" Without these mappings, `n` & `N` works fine. (These mappings just provide
" different highlight method and have some other features )

" I don't use these `n` and `N` mappings because they don't behavor well.
" map n <Plug>(easymotion-next)
" map N <Plug>(easymotion-prev)
" ########## for easymotion Plugin ########## 

" ########## for altercation/vim-colors-solarized Plugin ##########
syntax enable
set background=light
colorscheme solarized
" ########## for altercation/vim-colors-solarized Plugin ##########

" ########## for vim-airline/vim-airline Plugin ########## 
let g:airline#extensions#tabline#enabled = 1

" ########## for xolox/vim-session Plugin ##########

" ################### Plugin Configurations ##################### 
 
" #################### Abbreviations #################### 
iab c1 %%%%%%%%%%
iab c2 %%%%%%%%%%%%%%%%%%%%
iab c4 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
iab c6 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
iab cs1 ##########
iab cs2 ####################
iab cs4 ########################################
iab cs6 ############################################################

iab cfig %%%%%%%%%% fig:<++> %%%%%%%%%%
iab ctbl %%%%%%%%%% tbl:<++> %%%%%%%%%%
" #################### Abbreviations #################### 